-- Notifications + push (13 June 2026).
-- A single notifications feed, generated by DB triggers so events created from
-- the web (server actions) and the mobile app (direct supabase) both route
-- consistently. Each row carries a `type` + `data` (for localized in-app
-- rendering) and a pre-rendered English title/body (for push). Push is sent to
-- Expo via pg_net on insert.

create extension if not exists pg_net with schema extensions;

-- ============================================================================
-- tables
-- ============================================================================

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null,
  data jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index idx_notifications_user on public.notifications(user_id, created_at desc);
create index idx_notifications_unread on public.notifications(user_id) where read_at is null;

alter table public.notifications enable row level security;

create policy notifications_select_own on public.notifications
  for select using (user_id = auth.uid());
create policy notifications_update_own on public.notifications
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Expo push tokens (one device = one row).
create table public.push_tokens (
  user_id uuid not null references public.profiles(id) on delete cascade,
  token text not null,
  platform text,
  updated_at timestamptz not null default now(),
  primary key (user_id, token)
);
alter table public.push_tokens enable row level security;
create policy push_tokens_own on public.push_tokens
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ============================================================================
-- helpers
-- ============================================================================

-- Format paisa-precise numeric as a clean rupee string for push text.
create or replace function public.inr(n numeric)
returns text language sql immutable as $$
  select '₹' || trim(to_char(round(n), 'FM999G999G999G990'));
$$;

create or replace function public.add_notif(
  p_user uuid, p_type text, p_title text, p_body text, p_data jsonb
) returns void language plpgsql security definer set search_path = public as $$
begin
  if p_user is null then return; end if;
  insert into public.notifications (user_id, type, title, body, data)
  values (p_user, p_type, p_title, p_body, coalesce(p_data, '{}'::jsonb));
end; $$;

-- ============================================================================
-- money_requests → notifications
-- ============================================================================

create or replace function public.notify_money_request()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_retailer text;
  v_fos text;
  v_account text;
  v_data jsonb;
  v_amt numeric;
  fos_changed boolean;
  dist_changed boolean;
  is_auto boolean;
begin
  select full_name into v_retailer from public.profiles where id = NEW.retailer_id;
  select full_name into v_fos from public.profiles where id = NEW.fos_id;
  select name into v_account from public.accounts where id = NEW.account_id;
  v_retailer := coalesce(v_retailer, 'Retailer');

  if TG_OP = 'INSERT' then
    -- Manual adjustment (increase) is inserted already-approved.
    if NEW.distributor_status = 'approved'
       and coalesce(NEW.distributor_notes, '') like 'Manual adjustment by distributor%' then
      v_amt := coalesce(NEW.final_amount, NEW.requested_amount);
      perform add_notif(NEW.retailer_id, 'adjustment',
        'Balance adjusted',
        'Your outstanding was increased by ' || inr(v_amt) || ' on ' || coalesce(v_account,''),
        jsonb_build_object('request_id', NEW.id, 'amount', v_amt, 'account', v_account, 'direction', 'up'));
      return NEW;
    end if;
    -- Opening-balance / other bulk approved inserts: stay silent.
    if NEW.distributor_status = 'approved' then return NEW; end if;
    -- A real new pending request: FOS must act, distributor may act.
    perform add_notif(NEW.fos_id, 'req_new',
      'New money request',
      v_retailer || ' requested ' || inr(NEW.requested_amount) || ' on ' || coalesce(v_account,''),
      jsonb_build_object('request_id', NEW.id, 'retailer', v_retailer, 'amount', NEW.requested_amount, 'account', v_account));
    perform add_notif(NEW.distributor_id, 'req_new_dist',
      'New request (awaiting FOS)',
      v_retailer || ' requested ' || inr(NEW.requested_amount) || ' — ' || coalesce(v_fos,'FOS'),
      jsonb_build_object('request_id', NEW.id, 'retailer', v_retailer, 'fos', v_fos, 'amount', NEW.requested_amount, 'account', v_account));
    return NEW;
  end if;

  -- UPDATE
  fos_changed  := NEW.fos_status is distinct from OLD.fos_status;
  dist_changed := NEW.distributor_status is distinct from OLD.distributor_status;
  is_auto := dist_changed and NEW.distributor_status = 'approved'
             and coalesce(NEW.distributor_notes, '') like 'Auto-approved%';

  v_data := jsonb_build_object('request_id', NEW.id, 'retailer', v_retailer, 'fos', v_fos, 'account', v_account);

  if is_auto then
    v_amt := coalesce(NEW.final_amount, NEW.fos_amount, NEW.requested_amount);
    perform add_notif(NEW.retailer_id, 'req_approved',
      'Request approved', inr(v_amt) || ' approved on ' || coalesce(v_account,''),
      v_data || jsonb_build_object('amount', v_amt));
    perform add_notif(NEW.distributor_id, 'req_auto',
      'Auto-approved', v_retailer || ': ' || inr(v_amt) || ' (FOS authority)',
      v_data || jsonb_build_object('amount', v_amt));
    return NEW;
  end if;

  if fos_changed then
    if NEW.fos_status = 'accepted' then
      perform add_notif(NEW.retailer_id, 'req_fos_accepted',
        'Accepted by FOS', inr(coalesce(NEW.fos_amount, NEW.requested_amount)) || ' — awaiting distributor',
        v_data || jsonb_build_object('amount', coalesce(NEW.fos_amount, NEW.requested_amount)));
      perform add_notif(NEW.distributor_id, 'req_awaiting_dist',
        'Approval needed', v_retailer || ' ' || inr(coalesce(NEW.fos_amount, NEW.requested_amount)),
        v_data || jsonb_build_object('amount', coalesce(NEW.fos_amount, NEW.requested_amount)));
    elsif NEW.fos_status = 'edited' then
      perform add_notif(NEW.retailer_id, 'req_fos_edited',
        'Revised by FOS', 'Now ' || inr(NEW.fos_amount) || ' — awaiting distributor',
        v_data || jsonb_build_object('amount', NEW.fos_amount, 'requested', NEW.requested_amount));
      perform add_notif(NEW.distributor_id, 'req_awaiting_dist',
        'Approval needed', v_retailer || ' ' || inr(NEW.fos_amount),
        v_data || jsonb_build_object('amount', NEW.fos_amount));
    elsif NEW.fos_status = 'declined' then
      perform add_notif(NEW.retailer_id, 'req_declined',
        'Request declined', 'Declined by ' || coalesce(v_fos, 'FOS'),
        v_data || jsonb_build_object('by', 'fos'));
    end if;
  end if;

  if dist_changed then
    if NEW.distributor_status = 'approved' then
      v_amt := coalesce(NEW.final_amount, NEW.fos_amount, NEW.requested_amount);
      perform add_notif(NEW.retailer_id, 'req_approved',
        'Request approved', inr(v_amt) || ' approved on ' || coalesce(v_account,''),
        v_data || jsonb_build_object('amount', v_amt));
      perform add_notif(NEW.fos_id, 'req_approved_fos',
        'Distributor approved', v_retailer || ': ' || inr(v_amt),
        v_data || jsonb_build_object('amount', v_amt));
    elsif NEW.distributor_status = 'declined' then
      perform add_notif(NEW.retailer_id, 'req_declined',
        'Request declined', 'Declined by distributor',
        v_data || jsonb_build_object('by', 'distributor'));
      perform add_notif(NEW.fos_id, 'req_declined_fos',
        'Distributor declined', v_retailer || '''s request',
        v_data);
    end if;
  end if;

  return NEW;
end; $$;

create trigger trg_notify_money_request
  after insert or update on public.money_requests
  for each row execute function public.notify_money_request();

-- ============================================================================
-- cash_submissions → notifications
-- ============================================================================

create or replace function public.notify_cash_submission()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_retailer text;
  v_fos uuid;
  v_account text;
  v_amt numeric;
  v_data jsonb;
begin
  select full_name, fos_id into v_retailer, v_fos from public.profiles where id = NEW.retailer_id;
  select name into v_account from public.accounts where id = NEW.account_id;
  v_retailer := coalesce(v_retailer, 'Retailer');
  v_amt := coalesce(NEW.approved_amount, NEW.amount);
  v_data := jsonb_build_object('cash_id', NEW.id, 'retailer', v_retailer, 'amount', v_amt, 'account', v_account);

  if TG_OP = 'INSERT' then
    if NEW.status = 'approved'
       and coalesce(NEW.notes, '') like 'Manual adjustment by distributor%' then
      perform add_notif(NEW.retailer_id, 'adjustment',
        'Balance adjusted',
        'Your outstanding was reduced by ' || inr(v_amt) || ' on ' || coalesce(v_account,''),
        v_data || jsonb_build_object('direction', 'down'));
    elsif NEW.status = 'approved' then
      -- FOS submitted on the retailer's behalf (auto-approved).
      perform add_notif(NEW.retailer_id, 'cash_approved',
        'Cash recorded', inr(v_amt) || ' received on ' || coalesce(v_account,''), v_data);
      perform add_notif(NEW.distributor_id, 'cash_approved_dist',
        'Cash collected', v_retailer || ': ' || inr(v_amt), v_data);
    elsif NEW.status = 'pending' then
      perform add_notif(v_fos, 'cash_new',
        'Cash submitted', v_retailer || ' submitted ' || inr(NEW.amount) || ' on ' || coalesce(v_account,''),
        v_data || jsonb_build_object('amount', NEW.amount));
    end if;
    return NEW;
  end if;

  -- UPDATE: a pending submission decided.
  if NEW.status is distinct from OLD.status then
    if NEW.status = 'approved' then
      perform add_notif(NEW.retailer_id, 'cash_approved',
        'Cash approved', inr(v_amt) || ' received on ' || coalesce(v_account,''), v_data);
      perform add_notif(NEW.distributor_id, 'cash_approved_dist',
        'Cash collected', v_retailer || ': ' || inr(v_amt), v_data);
    elsif NEW.status = 'declined' then
      perform add_notif(NEW.retailer_id, 'cash_declined',
        'Cash declined', 'Your ' || inr(NEW.amount) || ' submission was declined',
        v_data || jsonb_build_object('amount', NEW.amount));
    end if;
  end if;
  return NEW;
end; $$;

create trigger trg_notify_cash_submission
  after insert or update on public.cash_submissions
  for each row execute function public.notify_cash_submission();

-- ============================================================================
-- push: send each new notification to the recipient's Expo devices
-- ============================================================================

create or replace function public.notify_push()
returns trigger language plpgsql security definer set search_path = public, extensions as $$
declare tok record;
begin
  for tok in select token from public.push_tokens where user_id = NEW.user_id loop
    perform net.http_post(
      url := 'https://exp.host/--/api/v2/push/send',
      headers := jsonb_build_object('Content-Type', 'application/json'),
      body := jsonb_build_object(
        'to', tok.token,
        'title', NEW.title,
        'body', NEW.body,
        'sound', 'default',
        'priority', 'high',
        'channelId', 'default',
        'data', NEW.data || jsonb_build_object('type', NEW.type, 'notification_id', NEW.id)
      )
    );
  end loop;
  return NEW;
end; $$;

create trigger trg_notify_push
  after insert on public.notifications
  for each row execute function public.notify_push();

-- ============================================================================
-- realtime: the in-app bell listens to its own notifications
-- ============================================================================

alter publication supabase_realtime add table public.notifications;
